image:
  repository: mdundek/dummy-starship-command
  tag: 2.1.3
  pullPolicy: Always

# imagePullSecrets: 
#  - name: my-dockerhub-secret

service:
  - name: http
    type: ClusterIP
    port: 3000
    targetPort: 3000

# ingress:
#   hostname: starship
#   targetService: http

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi