apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: polinux/stress
        args:
          [
            "stress",
            "--cpu", "{{ .Values.cpu }}",
            "--io", "{{ .Values.io }}",
            "--vm", "{{ .Values.vm }}",
            "--vm-bytes", "{{ .Values.vmbytes }}",
            "--timeout", "{{ .Values.timeout }}",
            "--verbose"
          ]
{{ toYaml .Values.resources | indent 8 }}