apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "starship-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "starship-app.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "starship-app.fullname" . }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: starship-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range .Values.service }}
            - containerPort: {{ .port }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}