{{- range .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: {{ .type | default "ClusterIP" }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if eq .type "NodePort" }}
      nodePort: {{ .nodePort }}
      {{- end }}
      name: {{ .name }}
  selector:
    app: {{ include "my-node-app.fullname" . }}
---
{{- end }}