replicaCount: 1

image:
  pullPolicy: IfNotPresent

cpu: "1"
io: "1"
vm: "1"
vmbytes: "128M"
timeout: "10s"

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi